### ISSUE TITLE
configure: error - Please provide a path to MagickWand-config

### ISSUE THREAD

**Issue by 4Syno** [EBOOST/php7fpm#1]
Hello,
I’m using your image on a synology diskstation;
after the docker create command the imagick php extension was missing.
**https://github.com/EBOOST/php7fpm/blob/master/Dockerfile#L14**

> configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.
> ERROR: `/tmp/pear/temp/imagick/configure --with-php-config=/usr/local/bin/php-config --with-imagick' failed

Looks like there are 2 packages missing
`apt-get install libmagickwand-dev libmagickcore-dev`
You should add "extension=imagick.so" to php.ini or docker-php-ext-image.ini for example.

Could you please take a closer look and perform the update?
Thanks you.

**Comment by BertvanHoekelen** [comment]
I have updated the Dockerfile and it should work fine now. Please close the issue if it's resolved.

**Comment by 4Syno** [comment]
Thanks a lot for your fast response ;) It works now!

**Pull complete
Status: Downloaded newer image for eboost/php7fpm:latest**
`
docker run --name=php7-1 -d eboost/php7fpm`
eec390a628f4985d7605f23a94b4793275fd78170565a25ec7593eaf2b24e82f
`docker exec -i -t php7-1 /bin/bash`
root@eec390a628f4:/var/www/html# php -m |grep imagick
imagick
